source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]
gem "bootsnap", require: false

# Auth
gem "devise"
gem "jwt"

# API
gem "rack-cors"
gem "rack-attack"
gem "blueprinter"
gem "kaminari"

# Analytics
gem "geocoder"
gem "browser"

# Background Jobs
gem "sidekiq"
gem "redis"

# QR Code
gem "rqrcode"

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ], require: "debug/prelude"
  gem "dotenv-rails"
  gem "faker"
end
